# version format
version: 1.5.{build}

# build only tags
skip_non_tags: true

# image
image: Visual Studio 2017

# build platform
platform: x64
configuration: Release

# clone directory
clone_folder: c:\xmrigCC

install:
  - mkdir c:\xmrigCC-deps
  - curl -sL https://github.com/Bendr0id/xmrigCC-deps/releases/download/v1/xmrigCC-deps.zip -o xmrigCC-deps.zip
  - 7z x xmrigCC-deps.zip -o"c:\xmrigCC-deps" -y > nul

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmrigCC
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DUV_INCLUDE_DIR="c:\xmrigCC-deps\msvc2017\libuv\x64\include" -DUV_LIBRARY="c:\xmrigCC-deps\msvc2017\libuv\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\msvc2017\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\xmrigCC-deps\msvc2017\libmicrohttpd\x64\lib\libmicrohttpd.lib" -DOPENSSL_MSVC_STATIC_RT=TRUE
  - msbuild xmrig.sln /p:Configuration=Release


after_build:
- cd c:\xmrigCC
- cmd: 7z a xmrigCC-mvc-win64.zip "c:\xmrigCC\build\Release\*.exe" "c:\xmrigCC\src\*config*" "c:\xmrigCC\index.html"
- cmd: dir

artifacts:
- path: xmrigCC-mvc-win64.zip
